<?xml version="1.0" encoding="utf-8"?>
<Database Name="Emmanuel" Class="adminDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MJLAPTOP01\SQLExpress;Initial Catalog=Emmanuel;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EmmanuelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.page" Member="pages">
    <Type Name="page">
      <Column Name="page_key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="page_fkey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pageid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="navtitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="accesskey" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="metadescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="metakeywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="thumbnailimage" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="showinnav" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="showinfeaturednav" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="showonhome" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="showinfooter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sortorder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="linkurl" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.banners" Member="banners">
    <Type Name="banner">
      <Column Name="bannerdid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="alttext" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="randomness" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.lookup" Member="lookups">
    <Type Name="lookup">
      <Column Name="lookup_key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lookup_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="active" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="lookup_article_category" Member="article_categories" ThisKey="lookup_key" OtherKey="category_fkey" Type="article_category" />
      <Association Name="lookup_Newsletter_Link" Member="Newsletter_Links" ThisKey="lookup_key" OtherKey="link_type_key" Type="Newsletter_Link" />
    </Type>
  </Table>
  <Table Name="dbo.article_categories" Member="article_categories">
    <Type Name="article_category">
      <Column Name="artcat_key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="article_fkey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category_fkey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="lookup_article_category" Member="lookup" ThisKey="category_fkey" OtherKey="lookup_key" Type="lookup" IsForeignKey="true" />
      <Association Name="article_article_category" Member="article" ThisKey="article_fkey" OtherKey="article_key" Type="article" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.articles" Member="articles">
    <Type Name="article">
      <Column Name="article_key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="shortdescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thumbnailimage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="acitve" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sortorder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="startdate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="enddate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="article_article_category" Member="article_categories" ThisKey="article_key" OtherKey="article_fkey" Type="article_category" />
    </Type>
  </Table>
  <Table Name="dbo.NewsletterReciprients" Member="NewsletterReciprients">
    <Type Name="NewsletterReciprient">
      <Column Name="reciprient_key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="confirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Newsletters" Member="Newsletters">
    <Type Name="Newsletter">
      <Column Name="Newsletter_Key" Member="newsletter_key" Storage="_Newsletter_Key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Member="subject" Storage="_Subject" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Body" Member="body" Storage="_Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Date_Sent" Member="date_sent" Storage="_Date_Sent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Member="date_created" AutoSync="OnInsert" Type="System.DateTime" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Newsletter_Newsletter_Link" Member="Newsletter_Links" ThisKey="newsletter_key" OtherKey="newsletter_key" Type="Newsletter_Link" />
    </Type>
  </Table>
  <Table Name="dbo.Newsletter_Links" Member="Newsletter_Links">
    <Type Name="Newsletter_Link">
      <Column Name="Newsletter_Link_Key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="newsletter_key" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="link_key" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="link_type_key" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="lookup_Newsletter_Link" Member="lookup" ThisKey="link_type_key" OtherKey="lookup_key" Type="lookup" IsForeignKey="true" />
      <Association Name="Newsletter_Newsletter_Link" Member="Newsletter" ThisKey="newsletter_key" OtherKey="newsletter_key" Type="Newsletter" IsForeignKey="true" />
    </Type>
  </Table>
</Database>