#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjjames.AdminSystem.DataContexts.Archive
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="CMSArchiveData")]
	public partial class archiveDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertarticle(mjjames.AdminSystem.DataEntities.Archive.article instance);
    partial void Updatearticle(mjjames.AdminSystem.DataEntities.Archive.article instance);
    partial void Deletearticle(mjjames.AdminSystem.DataEntities.Archive.article instance);
    partial void Inserttestimony(mjjames.AdminSystem.DataEntities.Archive.testimony instance);
    partial void Updatetestimony(mjjames.AdminSystem.DataEntities.Archive.testimony instance);
    partial void Deletetestimony(mjjames.AdminSystem.DataEntities.Archive.testimony instance);
    partial void Insertbanner(mjjames.AdminSystem.DataEntities.Archive.banner instance);
    partial void Updatebanner(mjjames.AdminSystem.DataEntities.Archive.banner instance);
    partial void Deletebanner(mjjames.AdminSystem.DataEntities.Archive.banner instance);
    partial void Insertmedia(mjjames.AdminSystem.DataEntities.Archive.media instance);
    partial void Updatemedia(mjjames.AdminSystem.DataEntities.Archive.media instance);
    partial void Deletemedia(mjjames.AdminSystem.DataEntities.Archive.media instance);
    partial void InsertNewsletterReciprient(mjjames.AdminSystem.DataEntities.Archive.NewsletterReciprient instance);
    partial void UpdateNewsletterReciprient(mjjames.AdminSystem.DataEntities.Archive.NewsletterReciprient instance);
    partial void DeleteNewsletterReciprient(mjjames.AdminSystem.DataEntities.Archive.NewsletterReciprient instance);
    partial void InsertNewsletter(mjjames.AdminSystem.DataEntities.Archive.Newsletter instance);
    partial void UpdateNewsletter(mjjames.AdminSystem.DataEntities.Archive.Newsletter instance);
    partial void DeleteNewsletter(mjjames.AdminSystem.DataEntities.Archive.Newsletter instance);
    partial void Insertoffer(mjjames.AdminSystem.DataEntities.Archive.offer instance);
    partial void Updateoffer(mjjames.AdminSystem.DataEntities.Archive.offer instance);
    partial void Deleteoffer(mjjames.AdminSystem.DataEntities.Archive.offer instance);
    partial void Insertpage(mjjames.AdminSystem.DataEntities.Archive.page instance);
    partial void Updatepage(mjjames.AdminSystem.DataEntities.Archive.page instance);
    partial void Deletepage(mjjames.AdminSystem.DataEntities.Archive.page instance);
    partial void Insertproject(mjjames.AdminSystem.DataEntities.Archive.project instance);
    partial void Updateproject(mjjames.AdminSystem.DataEntities.Archive.project instance);
    partial void Deleteproject(mjjames.AdminSystem.DataEntities.Archive.project instance);
    #endregion
		
		public archiveDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CMSArchiveDataConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public archiveDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public archiveDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public archiveDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public archiveDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.article> articles
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.article>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.testimony> testimonies
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.testimony>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.banner> banners
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.banner>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.media> medias
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.media>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.NewsletterReciprient> NewsletterReciprients
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.NewsletterReciprient>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.Newsletter> Newsletters
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.Newsletter>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.offer> offers
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.offer>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.page> pages
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.page>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.project> projects
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.project>();
			}
		}
		
		public System.Data.Linq.Table<mjjames.AdminSystem.DataEntities.Archive.v_recyleditem> v_recyleditems
		{
			get
			{
				return this.GetTable<mjjames.AdminSystem.DataEntities.Archive.v_recyleditem>();
			}
		}
	}
}
namespace mjjames.AdminSystem.DataEntities.Archive
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[Table(Name="dbo.articles")]
	public partial class article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _articles_archive_key;
		
		private string _DBName;
		
		private int _article_key;
		
		private string _title;
		
		private string _body;
		
		private bool _showonhome;
		
		private string _shortdescription;
		
		private string _thumbnailimage;
		
		private bool _active;
		
		private int _sortorder;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private bool _include_in_feed;
		
		private string _url;
		
		private string _virtualurl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onarticles_archive_keyChanging(int value);
    partial void Onarticles_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onarticle_keyChanging(int value);
    partial void Onarticle_keyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnshowonhomeChanging(bool value);
    partial void OnshowonhomeChanged();
    partial void OnshortdescriptionChanging(string value);
    partial void OnshortdescriptionChanged();
    partial void OnthumbnailimageChanging(string value);
    partial void OnthumbnailimageChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OnsortorderChanging(int value);
    partial void OnsortorderChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void Oninclude_in_feedChanging(bool value);
    partial void Oninclude_in_feedChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnvirtualurlChanging(string value);
    partial void OnvirtualurlChanged();
    #endregion
		
		public article()
		{
			OnCreated();
		}
		
		[Column(Storage="_articles_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int articles_archive_key
		{
			get
			{
				return this._articles_archive_key;
			}
			set
			{
				if ((this._articles_archive_key != value))
				{
					this.Onarticles_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._articles_archive_key = value;
					this.SendPropertyChanged("articles_archive_key");
					this.Onarticles_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_article_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int article_key
		{
			get
			{
				return this._article_key;
			}
			set
			{
				if ((this._article_key != value))
				{
					this.Onarticle_keyChanging(value);
					this.SendPropertyChanging();
					this._article_key = value;
					this.SendPropertyChanged("article_key");
					this.Onarticle_keyChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_body", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[Column(Storage="_showonhome", DbType="Bit NOT NULL")]
		public bool showonhome
		{
			get
			{
				return this._showonhome;
			}
			set
			{
				if ((this._showonhome != value))
				{
					this.OnshowonhomeChanging(value);
					this.SendPropertyChanging();
					this._showonhome = value;
					this.SendPropertyChanged("showonhome");
					this.OnshowonhomeChanged();
				}
			}
		}
		
		[Column(Storage="_shortdescription", DbType="NVarChar(MAX)")]
		public string shortdescription
		{
			get
			{
				return this._shortdescription;
			}
			set
			{
				if ((this._shortdescription != value))
				{
					this.OnshortdescriptionChanging(value);
					this.SendPropertyChanging();
					this._shortdescription = value;
					this.SendPropertyChanged("shortdescription");
					this.OnshortdescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_thumbnailimage", DbType="NVarChar(50)")]
		public string thumbnailimage
		{
			get
			{
				return this._thumbnailimage;
			}
			set
			{
				if ((this._thumbnailimage != value))
				{
					this.OnthumbnailimageChanging(value);
					this.SendPropertyChanging();
					this._thumbnailimage = value;
					this.SendPropertyChanged("thumbnailimage");
					this.OnthumbnailimageChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_sortorder", DbType="Int NOT NULL")]
		public int sortorder
		{
			get
			{
				return this._sortorder;
			}
			set
			{
				if ((this._sortorder != value))
				{
					this.OnsortorderChanging(value);
					this.SendPropertyChanging();
					this._sortorder = value;
					this.SendPropertyChanged("sortorder");
					this.OnsortorderChanged();
				}
			}
		}
		
		[Column(Storage="_start_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[Column(Storage="_end_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[Column(Storage="_include_in_feed", DbType="Bit NOT NULL")]
		public bool include_in_feed
		{
			get
			{
				return this._include_in_feed;
			}
			set
			{
				if ((this._include_in_feed != value))
				{
					this.Oninclude_in_feedChanging(value);
					this.SendPropertyChanging();
					this._include_in_feed = value;
					this.SendPropertyChanged("include_in_feed");
					this.Oninclude_in_feedChanged();
				}
			}
		}
		
		[Column(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[Column(Storage="_virtualurl", DbType="NVarChar(MAX)")]
		public string virtualurl
		{
			get
			{
				return this._virtualurl;
			}
			set
			{
				if ((this._virtualurl != value))
				{
					this.OnvirtualurlChanging(value);
					this.SendPropertyChanging();
					this._virtualurl = value;
					this.SendPropertyChanged("virtualurl");
					this.OnvirtualurlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.testimonies")]
	public partial class testimony : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _testimony_archive_key;
		
		private string _DBName;
		
		private int _testimony_key;
		
		private string _title;
		
		private string _description;
		
		private System.Nullable<int> _project_fkey;
		
		private bool _active;
		
		private string _video_id;
		
		private string _url;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontestimonies_archive_keyChanging(int value);
    partial void Ontestimonies_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Ontestimony_keyChanging(int value);
    partial void Ontestimony_keyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onproject_fkeyChanging(System.Nullable<int> value);
    partial void Onproject_fkeyChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void Onvideo_idChanging(string value);
    partial void Onvideo_idChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    #endregion
		
		public testimony()
		{
			OnCreated();
		}
		
		[Column(Storage="_testimony_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int testimonies_archive_key
		{
			get
			{
				return this._testimony_archive_key;
			}
			set
			{
				if ((this._testimony_archive_key != value))
				{
					this.Ontestimonies_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._testimony_archive_key = value;
					this.SendPropertyChanged("testimonies_archive_key");
					this.Ontestimonies_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_testimony_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int testimony_key
		{
			get
			{
				return this._testimony_key;
			}
			set
			{
				if ((this._testimony_key != value))
				{
					this.Ontestimony_keyChanging(value);
					this.SendPropertyChanging();
					this._testimony_key = value;
					this.SendPropertyChanged("testimony_key");
					this.Ontestimony_keyChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_project_fkey", DbType="Int")]
		public System.Nullable<int> project_fkey
		{
			get
			{
				return this._project_fkey;
			}
			set
			{
				if ((this._project_fkey != value))
				{
					this.Onproject_fkeyChanging(value);
					this.SendPropertyChanging();
					this._project_fkey = value;
					this.SendPropertyChanged("project_fkey");
					this.Onproject_fkeyChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_video_id", DbType="NVarChar(50)")]
		public string video_id
		{
			get
			{
				return this._video_id;
			}
			set
			{
				if ((this._video_id != value))
				{
					this.Onvideo_idChanging(value);
					this.SendPropertyChanging();
					this._video_id = value;
					this.SendPropertyChanged("video_id");
					this.Onvideo_idChanged();
				}
			}
		}
		
		[Column(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.banners")]
	public partial class banner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _banner_archive_key;
		
		private string _DBName;
		
		private int _bannerdid;
		
		private string _name;
		
		private string _image;
		
		private string _alttext;
		
		private string _url;
		
		private string _category;
		
		private int _randomness;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbanners_archive_keyChanging(int value);
    partial void Onbanners_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void OnbannerdidChanging(int value);
    partial void OnbannerdidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnalttextChanging(string value);
    partial void OnalttextChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OnrandomnessChanging(int value);
    partial void OnrandomnessChanged();
    #endregion
		
		public banner()
		{
			OnCreated();
		}
		
		[Column(Storage="_banner_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int banners_archive_key
		{
			get
			{
				return this._banner_archive_key;
			}
			set
			{
				if ((this._banner_archive_key != value))
				{
					this.Onbanners_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._banner_archive_key = value;
					this.SendPropertyChanged("banners_archive_key");
					this.Onbanners_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_bannerdid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int bannerdid
		{
			get
			{
				return this._bannerdid;
			}
			set
			{
				if ((this._bannerdid != value))
				{
					this.OnbannerdidChanging(value);
					this.SendPropertyChanging();
					this._bannerdid = value;
					this.SendPropertyChanged("bannerdid");
					this.OnbannerdidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_image", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[Column(Storage="_alttext", DbType="NVarChar(MAX)")]
		public string alttext
		{
			get
			{
				return this._alttext;
			}
			set
			{
				if ((this._alttext != value))
				{
					this.OnalttextChanging(value);
					this.SendPropertyChanging();
					this._alttext = value;
					this.SendPropertyChanged("alttext");
					this.OnalttextChanged();
				}
			}
		}
		
		[Column(Storage="_url", DbType="NVarChar(255)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[Column(Storage="_category", DbType="NVarChar(20)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[Column(Storage="_randomness", DbType="Int NOT NULL")]
		public int randomness
		{
			get
			{
				return this._randomness;
			}
			set
			{
				if ((this._randomness != value))
				{
					this.OnrandomnessChanging(value);
					this.SendPropertyChanging();
					this._randomness = value;
					this.SendPropertyChanged("randomness");
					this.OnrandomnessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.media")]
	public partial class media : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _media_archive_key;
		
		private string _DBName;
		
		private int _media_key;
		
		private string _title;
		
		private string _description;
		
		private string _filename;
		
		private int _mediatype_lookup;
		
		private bool _active;
		
		private string _link;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmedia_archive_keyChanging(int value);
    partial void Onmedia_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onmedia_keyChanging(int value);
    partial void Onmedia_keyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void Onmediatype_lookupChanging(int value);
    partial void Onmediatype_lookupChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public media()
		{
			OnCreated();
		}
		
		[Column(Storage="_media_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int media_archive_key
		{
			get
			{
				return this._media_archive_key;
			}
			set
			{
				if ((this._media_archive_key != value))
				{
					this.Onmedia_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._media_archive_key = value;
					this.SendPropertyChanged("media_archive_key");
					this.Onmedia_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_media_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int media_key
		{
			get
			{
				return this._media_key;
			}
			set
			{
				if ((this._media_key != value))
				{
					this.Onmedia_keyChanging(value);
					this.SendPropertyChanging();
					this._media_key = value;
					this.SendPropertyChanged("media_key");
					this.Onmedia_keyChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_filename", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[Column(Storage="_mediatype_lookup", DbType="Int NOT NULL")]
		public int mediatype_lookup
		{
			get
			{
				return this._mediatype_lookup;
			}
			set
			{
				if ((this._mediatype_lookup != value))
				{
					this.Onmediatype_lookupChanging(value);
					this.SendPropertyChanging();
					this._mediatype_lookup = value;
					this.SendPropertyChanged("mediatype_lookup");
					this.Onmediatype_lookupChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_link", DbType="NVarChar(MAX)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.NewsletterReciprients")]
	public partial class NewsletterReciprient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _newsletter_reciprients_archive_key;
		
		private string _DBName;
		
		private int _reciprient_key;
		
		private string _name;
		
		private string _email;
		
		private bool _active;
		
		private bool _confirmed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnewsletter_reciprients_archive_keyChanging(int value);
    partial void Onnewsletter_reciprients_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onreciprient_keyChanging(int value);
    partial void Onreciprient_keyChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OnconfirmedChanging(bool value);
    partial void OnconfirmedChanged();
    #endregion
		
		public NewsletterReciprient()
		{
			OnCreated();
		}
		
		[Column(Storage="_newsletter_reciprients_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int newsletter_reciprients_archive_key
		{
			get
			{
				return this._newsletter_reciprients_archive_key;
			}
			set
			{
				if ((this._newsletter_reciprients_archive_key != value))
				{
					this.Onnewsletter_reciprients_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._newsletter_reciprients_archive_key = value;
					this.SendPropertyChanged("newsletter_reciprients_archive_key");
					this.Onnewsletter_reciprients_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_reciprient_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int reciprient_key
		{
			get
			{
				return this._reciprient_key;
			}
			set
			{
				if ((this._reciprient_key != value))
				{
					this.Onreciprient_keyChanging(value);
					this.SendPropertyChanging();
					this._reciprient_key = value;
					this.SendPropertyChanged("reciprient_key");
					this.Onreciprient_keyChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_confirmed", DbType="Bit NOT NULL")]
		public bool confirmed
		{
			get
			{
				return this._confirmed;
			}
			set
			{
				if ((this._confirmed != value))
				{
					this.OnconfirmedChanging(value);
					this.SendPropertyChanging();
					this._confirmed = value;
					this.SendPropertyChanged("confirmed");
					this.OnconfirmedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Newsletters")]
	public partial class Newsletter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _newsletter_archive_key;
		
		private string _DBName;
		
		private int _newsletter_key;
		
		private string _subject;
		
		private string _body;
		
		private System.Nullable<System.DateTime> _date_sent;
		
		private System.DateTime _date_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnewsletters_archive_keyChanging(int value);
    partial void Onnewsletters_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onnewsletter_keyChanging(int value);
    partial void Onnewsletter_keyChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void Ondate_sentChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_sentChanged();
    partial void Ondate_createdChanging(System.DateTime value);
    partial void Ondate_createdChanged();
    #endregion
		
		public Newsletter()
		{
			OnCreated();
		}
		
		[Column(Storage="_newsletter_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int newsletters_archive_key
		{
			get
			{
				return this._newsletter_archive_key;
			}
			set
			{
				if ((this._newsletter_archive_key != value))
				{
					this.Onnewsletters_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._newsletter_archive_key = value;
					this.SendPropertyChanged("newsletters_archive_key");
					this.Onnewsletters_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_newsletter_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int newsletter_key
		{
			get
			{
				return this._newsletter_key;
			}
			set
			{
				if ((this._newsletter_key != value))
				{
					this.Onnewsletter_keyChanging(value);
					this.SendPropertyChanging();
					this._newsletter_key = value;
					this.SendPropertyChanged("newsletter_key");
					this.Onnewsletter_keyChanged();
				}
			}
		}
		
		[Column(Storage="_subject", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[Column(Storage="_body", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[Column(Storage="_date_sent", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_sent
		{
			get
			{
				return this._date_sent;
			}
			set
			{
				if ((this._date_sent != value))
				{
					this.Ondate_sentChanging(value);
					this.SendPropertyChanging();
					this._date_sent = value;
					this.SendPropertyChanged("date_sent");
					this.Ondate_sentChanged();
				}
			}
		}
		
		[Column(Storage="_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime date_created
		{
			get
			{
				return this._date_created;
			}
			set
			{
				if ((this._date_created != value))
				{
					this.Ondate_createdChanging(value);
					this.SendPropertyChanging();
					this._date_created = value;
					this.SendPropertyChanged("date_created");
					this.Ondate_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.offers")]
	public partial class offer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _offers_archive_key;
		
		private string _DBName;
		
		private int _offer_key;
		
		private string _title;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _offer_start;
		
		private System.Nullable<System.DateTime> _offer_end;
		
		private bool _active;
		
		private bool _showonhome;
		
		private bool _showinfeed;
		
		private string _url;
		
		private string _shortdescription;
		
		private string _thumbnailimage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onoffers_archive_keyChanging(int value);
    partial void Onoffers_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onoffer_keyChanging(int value);
    partial void Onoffer_keyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onoffer_startChanging(System.Nullable<System.DateTime> value);
    partial void Onoffer_startChanged();
    partial void Onoffer_endChanging(System.Nullable<System.DateTime> value);
    partial void Onoffer_endChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OnshowonhomeChanging(bool value);
    partial void OnshowonhomeChanged();
    partial void OnshowinfeedChanging(bool value);
    partial void OnshowinfeedChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnshortdescriptionChanging(string value);
    partial void OnshortdescriptionChanged();
    partial void OnthumbnailimageChanging(string value);
    partial void OnthumbnailimageChanged();
    #endregion
		
		public offer()
		{
			OnCreated();
		}
		
		[Column(Storage="_offers_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int offers_archive_key
		{
			get
			{
				return this._offers_archive_key;
			}
			set
			{
				if ((this._offers_archive_key != value))
				{
					this.Onoffers_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._offers_archive_key = value;
					this.SendPropertyChanged("offers_archive_key");
					this.Onoffers_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_offer_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int offer_key
		{
			get
			{
				return this._offer_key;
			}
			set
			{
				if ((this._offer_key != value))
				{
					this.Onoffer_keyChanging(value);
					this.SendPropertyChanging();
					this._offer_key = value;
					this.SendPropertyChanged("offer_key");
					this.Onoffer_keyChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_offer_start", DbType="Date")]
		public System.Nullable<System.DateTime> offer_start
		{
			get
			{
				return this._offer_start;
			}
			set
			{
				if ((this._offer_start != value))
				{
					this.Onoffer_startChanging(value);
					this.SendPropertyChanging();
					this._offer_start = value;
					this.SendPropertyChanged("offer_start");
					this.Onoffer_startChanged();
				}
			}
		}
		
		[Column(Storage="_offer_end", DbType="Date")]
		public System.Nullable<System.DateTime> offer_end
		{
			get
			{
				return this._offer_end;
			}
			set
			{
				if ((this._offer_end != value))
				{
					this.Onoffer_endChanging(value);
					this.SendPropertyChanging();
					this._offer_end = value;
					this.SendPropertyChanged("offer_end");
					this.Onoffer_endChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_showonhome", DbType="Bit NOT NULL")]
		public bool showonhome
		{
			get
			{
				return this._showonhome;
			}
			set
			{
				if ((this._showonhome != value))
				{
					this.OnshowonhomeChanging(value);
					this.SendPropertyChanging();
					this._showonhome = value;
					this.SendPropertyChanged("showonhome");
					this.OnshowonhomeChanged();
				}
			}
		}
		
		[Column(Storage="_showinfeed", DbType="Bit NOT NULL")]
		public bool showinfeed
		{
			get
			{
				return this._showinfeed;
			}
			set
			{
				if ((this._showinfeed != value))
				{
					this.OnshowinfeedChanging(value);
					this.SendPropertyChanging();
					this._showinfeed = value;
					this.SendPropertyChanged("showinfeed");
					this.OnshowinfeedChanged();
				}
			}
		}
		
		[Column(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[Column(Storage="_shortdescription", DbType="NVarChar(MAX)")]
		public string shortdescription
		{
			get
			{
				return this._shortdescription;
			}
			set
			{
				if ((this._shortdescription != value))
				{
					this.OnshortdescriptionChanging(value);
					this.SendPropertyChanging();
					this._shortdescription = value;
					this.SendPropertyChanged("shortdescription");
					this.OnshortdescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_thumbnailimage", DbType="NVarChar(50)")]
		public string thumbnailimage
		{
			get
			{
				return this._thumbnailimage;
			}
			set
			{
				if ((this._thumbnailimage != value))
				{
					this.OnthumbnailimageChanging(value);
					this.SendPropertyChanging();
					this._thumbnailimage = value;
					this.SendPropertyChanged("thumbnailimage");
					this.OnthumbnailimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.pages")]
	public partial class page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _page_archive_key;
		
		private string _DBName;
		
		private int _page_key;
		
		private System.Nullable<int> _page_fkey;
		
		private string _pageid;
		
		private string _navtitle;
		
		private System.Nullable<char> _accesskey;
		
		private string _metadescription;
		
		private string _metakeywords;
		
		private string _title;
		
		private string _body;
		
		private string _thumbnailimage;
		
		private System.Nullable<bool> _showinnav;
		
		private System.Nullable<bool> _showinfeaturednav;
		
		private System.Nullable<bool> _showonhome;
		
		private System.Nullable<bool> _showinfooter;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<int> _sortorder;
		
		private string _linkurl;
		
		private System.DateTime _lastmodified;
		
		private string _page_url;
		
		private System.Nullable<bool> _passwordprotect;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpages_archive_keyChanging(int value);
    partial void Onpages_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onpage_keyChanging(int value);
    partial void Onpage_keyChanged();
    partial void Onpage_fkeyChanging(System.Nullable<int> value);
    partial void Onpage_fkeyChanged();
    partial void OnpageidChanging(string value);
    partial void OnpageidChanged();
    partial void OnnavtitleChanging(string value);
    partial void OnnavtitleChanged();
    partial void OnaccesskeyChanging(System.Nullable<char> value);
    partial void OnaccesskeyChanged();
    partial void OnmetadescriptionChanging(string value);
    partial void OnmetadescriptionChanged();
    partial void OnmetakeywordsChanging(string value);
    partial void OnmetakeywordsChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnthumbnailimageChanging(string value);
    partial void OnthumbnailimageChanged();
    partial void OnshowinnavChanging(System.Nullable<bool> value);
    partial void OnshowinnavChanged();
    partial void OnshowinfeaturednavChanging(System.Nullable<bool> value);
    partial void OnshowinfeaturednavChanged();
    partial void OnshowonhomeChanging(System.Nullable<bool> value);
    partial void OnshowonhomeChanged();
    partial void OnshowinfooterChanging(System.Nullable<bool> value);
    partial void OnshowinfooterChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnsortorderChanging(System.Nullable<int> value);
    partial void OnsortorderChanged();
    partial void OnlinkurlChanging(string value);
    partial void OnlinkurlChanged();
    partial void OnlastmodifiedChanging(System.DateTime value);
    partial void OnlastmodifiedChanged();
    partial void Onpage_urlChanging(string value);
    partial void Onpage_urlChanged();
    partial void OnpasswordprotectChanging(System.Nullable<bool> value);
    partial void OnpasswordprotectChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public page()
		{
			OnCreated();
		}
		
		[Column(Storage="_page_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int pages_archive_key
		{
			get
			{
				return this._page_archive_key;
			}
			set
			{
				if ((this._page_archive_key != value))
				{
					this.Onpages_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._page_archive_key = value;
					this.SendPropertyChanged("pages_archive_key");
					this.Onpages_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_page_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int page_key
		{
			get
			{
				return this._page_key;
			}
			set
			{
				if ((this._page_key != value))
				{
					this.Onpage_keyChanging(value);
					this.SendPropertyChanging();
					this._page_key = value;
					this.SendPropertyChanged("page_key");
					this.Onpage_keyChanged();
				}
			}
		}
		
		[Column(Storage="_page_fkey", DbType="Int")]
		public System.Nullable<int> page_fkey
		{
			get
			{
				return this._page_fkey;
			}
			set
			{
				if ((this._page_fkey != value))
				{
					this.Onpage_fkeyChanging(value);
					this.SendPropertyChanging();
					this._page_fkey = value;
					this.SendPropertyChanged("page_fkey");
					this.Onpage_fkeyChanged();
				}
			}
		}
		
		[Column(Storage="_pageid", DbType="NVarChar(50)")]
		public string pageid
		{
			get
			{
				return this._pageid;
			}
			set
			{
				if ((this._pageid != value))
				{
					this.OnpageidChanging(value);
					this.SendPropertyChanging();
					this._pageid = value;
					this.SendPropertyChanged("pageid");
					this.OnpageidChanged();
				}
			}
		}
		
		[Column(Storage="_navtitle", DbType="NVarChar(50)")]
		public string navtitle
		{
			get
			{
				return this._navtitle;
			}
			set
			{
				if ((this._navtitle != value))
				{
					this.OnnavtitleChanging(value);
					this.SendPropertyChanging();
					this._navtitle = value;
					this.SendPropertyChanged("navtitle");
					this.OnnavtitleChanged();
				}
			}
		}
		
		[Column(Storage="_accesskey", DbType="NChar(1)")]
		public System.Nullable<char> accesskey
		{
			get
			{
				return this._accesskey;
			}
			set
			{
				if ((this._accesskey != value))
				{
					this.OnaccesskeyChanging(value);
					this.SendPropertyChanging();
					this._accesskey = value;
					this.SendPropertyChanged("accesskey");
					this.OnaccesskeyChanged();
				}
			}
		}
		
		[Column(Storage="_metadescription", DbType="NVarChar(MAX)")]
		public string metadescription
		{
			get
			{
				return this._metadescription;
			}
			set
			{
				if ((this._metadescription != value))
				{
					this.OnmetadescriptionChanging(value);
					this.SendPropertyChanging();
					this._metadescription = value;
					this.SendPropertyChanged("metadescription");
					this.OnmetadescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_metakeywords", DbType="NVarChar(MAX)")]
		public string metakeywords
		{
			get
			{
				return this._metakeywords;
			}
			set
			{
				if ((this._metakeywords != value))
				{
					this.OnmetakeywordsChanging(value);
					this.SendPropertyChanging();
					this._metakeywords = value;
					this.SendPropertyChanged("metakeywords");
					this.OnmetakeywordsChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_body", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[Column(Storage="_thumbnailimage", DbType="NVarChar(128)")]
		public string thumbnailimage
		{
			get
			{
				return this._thumbnailimage;
			}
			set
			{
				if ((this._thumbnailimage != value))
				{
					this.OnthumbnailimageChanging(value);
					this.SendPropertyChanging();
					this._thumbnailimage = value;
					this.SendPropertyChanged("thumbnailimage");
					this.OnthumbnailimageChanged();
				}
			}
		}
		
		[Column(Storage="_showinnav", DbType="Bit")]
		public System.Nullable<bool> showinnav
		{
			get
			{
				return this._showinnav;
			}
			set
			{
				if ((this._showinnav != value))
				{
					this.OnshowinnavChanging(value);
					this.SendPropertyChanging();
					this._showinnav = value;
					this.SendPropertyChanged("showinnav");
					this.OnshowinnavChanged();
				}
			}
		}
		
		[Column(Storage="_showinfeaturednav", DbType="Bit")]
		public System.Nullable<bool> showinfeaturednav
		{
			get
			{
				return this._showinfeaturednav;
			}
			set
			{
				if ((this._showinfeaturednav != value))
				{
					this.OnshowinfeaturednavChanging(value);
					this.SendPropertyChanging();
					this._showinfeaturednav = value;
					this.SendPropertyChanged("showinfeaturednav");
					this.OnshowinfeaturednavChanged();
				}
			}
		}
		
		[Column(Storage="_showonhome", DbType="Bit")]
		public System.Nullable<bool> showonhome
		{
			get
			{
				return this._showonhome;
			}
			set
			{
				if ((this._showonhome != value))
				{
					this.OnshowonhomeChanging(value);
					this.SendPropertyChanging();
					this._showonhome = value;
					this.SendPropertyChanged("showonhome");
					this.OnshowonhomeChanged();
				}
			}
		}
		
		[Column(Storage="_showinfooter", DbType="Bit")]
		public System.Nullable<bool> showinfooter
		{
			get
			{
				return this._showinfooter;
			}
			set
			{
				if ((this._showinfooter != value))
				{
					this.OnshowinfooterChanging(value);
					this.SendPropertyChanging();
					this._showinfooter = value;
					this.SendPropertyChanged("showinfooter");
					this.OnshowinfooterChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_sortorder", DbType="Int")]
		public System.Nullable<int> sortorder
		{
			get
			{
				return this._sortorder;
			}
			set
			{
				if ((this._sortorder != value))
				{
					this.OnsortorderChanging(value);
					this.SendPropertyChanging();
					this._sortorder = value;
					this.SendPropertyChanged("sortorder");
					this.OnsortorderChanged();
				}
			}
		}
		
		[Column(Storage="_linkurl", DbType="NVarChar(50)")]
		public string linkurl
		{
			get
			{
				return this._linkurl;
			}
			set
			{
				if ((this._linkurl != value))
				{
					this.OnlinkurlChanging(value);
					this.SendPropertyChanging();
					this._linkurl = value;
					this.SendPropertyChanged("linkurl");
					this.OnlinkurlChanged();
				}
			}
		}
		
		[Column(Storage="_lastmodified", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime lastmodified
		{
			get
			{
				return this._lastmodified;
			}
			set
			{
				if ((this._lastmodified != value))
				{
					this.OnlastmodifiedChanging(value);
					this.SendPropertyChanging();
					this._lastmodified = value;
					this.SendPropertyChanged("lastmodified");
					this.OnlastmodifiedChanged();
				}
			}
		}
		
		[Column(Storage="_page_url", DbType="NVarChar(MAX)")]
		public string page_url
		{
			get
			{
				return this._page_url;
			}
			set
			{
				if ((this._page_url != value))
				{
					this.Onpage_urlChanging(value);
					this.SendPropertyChanging();
					this._page_url = value;
					this.SendPropertyChanged("page_url");
					this.Onpage_urlChanged();
				}
			}
		}
		
		[Column(Storage="_passwordprotect", DbType="Bit NOT NULL")]
		public System.Nullable<bool> passwordprotect
		{
			get
			{
				return this._passwordprotect;
			}
			set
			{
				if ((this._passwordprotect != value))
				{
					this.OnpasswordprotectChanging(value);
					this.SendPropertyChanging();
					this._passwordprotect = value;
					this.SendPropertyChanged("passwordprotect");
					this.OnpasswordprotectChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="NVarChar(12)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.projects")]
	public partial class project : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _project_archive_key;
		
		private string _DBName;
		
		private int _project_key;
		
		private string _title;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private bool _active;
		
		private bool _include_in_rss;
		
		private string _photogallery_id;
		
		private string _video_id;
		
		private string _url;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprojects_archive_keyChanging(int value);
    partial void Onprojects_archive_keyChanged();
    partial void OnDBNameChanging(string value);
    partial void OnDBNameChanged();
    partial void Onproject_keyChanging(int value);
    partial void Onproject_keyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void Oninclude_in_rssChanging(bool value);
    partial void Oninclude_in_rssChanged();
    partial void Onphotogallery_idChanging(string value);
    partial void Onphotogallery_idChanged();
    partial void Onvideo_idChanging(string value);
    partial void Onvideo_idChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    #endregion
		
		public project()
		{
			OnCreated();
		}
		
		[Column(Storage="_project_archive_key", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int projects_archive_key
		{
			get
			{
				return this._project_archive_key;
			}
			set
			{
				if ((this._project_archive_key != value))
				{
					this.Onprojects_archive_keyChanging(value);
					this.SendPropertyChanging();
					this._project_archive_key = value;
					this.SendPropertyChanged("projects_archive_key");
					this.Onprojects_archive_keyChanged();
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this.OnDBNameChanging(value);
					this.SendPropertyChanging();
					this._DBName = value;
					this.SendPropertyChanged("DBName");
					this.OnDBNameChanged();
				}
			}
		}
		
		[Column(Storage="_project_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int project_key
		{
			get
			{
				return this._project_key;
			}
			set
			{
				if ((this._project_key != value))
				{
					this.Onproject_keyChanging(value);
					this.SendPropertyChanging();
					this._project_key = value;
					this.SendPropertyChanged("project_key");
					this.Onproject_keyChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_start_date", DbType="Date")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[Column(Storage="_end_date", DbType="Date")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Column(Storage="_include_in_rss", DbType="Bit NOT NULL")]
		public bool include_in_rss
		{
			get
			{
				return this._include_in_rss;
			}
			set
			{
				if ((this._include_in_rss != value))
				{
					this.Oninclude_in_rssChanging(value);
					this.SendPropertyChanging();
					this._include_in_rss = value;
					this.SendPropertyChanged("include_in_rss");
					this.Oninclude_in_rssChanged();
				}
			}
		}
		
		[Column(Storage="_photogallery_id", DbType="NVarChar(50)")]
		public string photogallery_id
		{
			get
			{
				return this._photogallery_id;
			}
			set
			{
				if ((this._photogallery_id != value))
				{
					this.Onphotogallery_idChanging(value);
					this.SendPropertyChanging();
					this._photogallery_id = value;
					this.SendPropertyChanged("photogallery_id");
					this.Onphotogallery_idChanged();
				}
			}
		}
		
		[Column(Storage="_video_id", DbType="NVarChar(50)")]
		public string video_id
		{
			get
			{
				return this._video_id;
			}
			set
			{
				if ((this._video_id != value))
				{
					this.Onvideo_idChanging(value);
					this.SendPropertyChanging();
					this._video_id = value;
					this.SendPropertyChanged("video_id");
					this.Onvideo_idChanged();
				}
			}
		}
		
		[Column(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.v_recyleditems")]
	public partial class v_recyleditem
	{
		
		private int _Key;
		
		private string _DBName;
		
		private string _Title;
		
		private string _Type;
		
		public v_recyleditem()
		{
		}
		
		[Column(Name="[KEY]", Storage="_Key", DbType="Int NOT NULL")]
		public int Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[Column(Storage="_DBName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DBName
		{
			get
			{
				return this._DBName;
			}
			set
			{
				if ((this._DBName != value))
				{
					this._DBName = value;
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[Column(Name="TYPE", Storage="_Type", DbType="VarChar(21) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
