//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjjames.AdminSystem.authentication {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Label lblMsg;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl labelUserName;
		
		protected System.Web.UI.HtmlControls.HtmlInputText inputUserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator vUserName;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl labelPassword;
		
		protected System.Web.UI.HtmlControls.HtmlInputText inputPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator vPassword;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton btnLogon;
	}
}
